// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package payappmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the PayAppModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_ACT_User_RegisterBuilder(
		payappmodule.proxies.Register _register
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_ACT_User_Register");
		builder = builder.withParam("Register", _register);
		return builder;
	}

	public static void mF_ACT_User_Register(
		IContext context,
		payappmodule.proxies.Register _register
	)
	{
		mF_ACT_User_RegisterBuilder(
				_register
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Add_PM_BankAccountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_Add_PM_BankAccount");
		return builder;
	}

	public static payappmodule.proxies.PaymentMethods mF_Add_PM_BankAccount(IContext context)
	{
		Object result = mF_Add_PM_BankAccountBuilder().execute(context);
		return result == null ? null : payappmodule.proxies.PaymentMethods.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Add_PM_CreditCardBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_Add_PM_CreditCard");
		return builder;
	}

	public static payappmodule.proxies.PaymentMethods mF_Add_PM_CreditCard(IContext context)
	{
		Object result = mF_Add_PM_CreditCardBuilder().execute(context);
		return result == null ? null : payappmodule.proxies.PaymentMethods.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_CardPaymentBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_CardPayment");
		return builder;
	}

	public static payappmodule.proxies.CardPayments mF_CardPayment(IContext context)
	{
		Object result = mF_CardPaymentBuilder().execute(context);
		return result == null ? null : payappmodule.proxies.CardPayments.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_CheckValid_Transfer_ByAccBuilder(
		payappmodule.proxies.TransactionsByAccount _transactions
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_CheckValid_Transfer_ByAcc");
		builder = builder.withParam("Transactions", _transactions);
		return builder;
	}

	public static boolean mF_CheckValid_Transfer_ByAcc(
		IContext context,
		payappmodule.proxies.TransactionsByAccount _transactions
	)
	{
		Object result = mF_CheckValid_Transfer_ByAccBuilder(
				_transactions
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_CheckValid_Transfer_ByCardBuilder(
		payappmodule.proxies.CardPayments _cardPayments
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_CheckValid_Transfer_ByCard");
		builder = builder.withParam("CardPayments", _cardPayments);
		return builder;
	}

	public static boolean mF_CheckValid_Transfer_ByCard(
		IContext context,
		payappmodule.proxies.CardPayments _cardPayments
	)
	{
		Object result = mF_CheckValid_Transfer_ByCardBuilder(
				_cardPayments
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_CheckValidations_RegisterBuilder(
		payappmodule.proxies.Register _register
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_CheckValidations_Register");
		builder = builder.withParam("Register", _register);
		return builder;
	}

	public static boolean mF_CheckValidations_Register(
		IContext context,
		payappmodule.proxies.Register _register
	)
	{
		Object result = mF_CheckValidations_RegisterBuilder(
				_register
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_CurrentUserBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_CurrentUser");
		return builder;
	}

	public static administration.proxies.Account mF_CurrentUser(IContext context)
	{
		Object result = mF_CurrentUserBuilder().execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_RegisterBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_Register");
		return builder;
	}

	public static payappmodule.proxies.Register mF_Register(IContext context)
	{
		Object result = mF_RegisterBuilder().execute(context);
		return result == null ? null : payappmodule.proxies.Register.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_SimulateTransfer_ByAccountBuilder(
		payappmodule.proxies.TransactionsByAccount _transactions
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_SimulateTransfer_ByAccount");
		builder = builder.withParam("Transactions", _transactions);
		return builder;
	}

	public static void mF_SimulateTransfer_ByAccount(
		IContext context,
		payappmodule.proxies.TransactionsByAccount _transactions
	)
	{
		mF_SimulateTransfer_ByAccountBuilder(
				_transactions
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_SimulateTransfer_ByCardBuilder(
		payappmodule.proxies.CardPayments _cardPayments
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_SimulateTransfer_ByCard");
		builder = builder.withParam("CardPayments", _cardPayments);
		return builder;
	}

	public static void mF_SimulateTransfer_ByCard(
		IContext context,
		payappmodule.proxies.CardPayments _cardPayments
	)
	{
		mF_SimulateTransfer_ByCardBuilder(
				_cardPayments
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_TransferByAccountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("PayAppModule.MF_TransferByAccount");
		return builder;
	}

	public static payappmodule.proxies.TransactionsByAccount mF_TransferByAccount(IContext context)
	{
		Object result = mF_TransferByAccountBuilder().execute(context);
		return result == null ? null : payappmodule.proxies.TransactionsByAccount.initialize(context, (IMendixObject) result);
	}
}
