// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package payappmodule.proxies;

public class CardPayments implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cardPaymentsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PayAppModule.CardPayments";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CardPaymentID("CardPaymentID"),
		Username("Username"),
		Amount("Amount"),
		Status("Status"),
		MerchantName("MerchantName"),
		Date("Date"),
		Currency("Currency"),
		CardPayments_PaymentMethods("PayAppModule.CardPayments_PaymentMethods");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CardPayments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CardPayments(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cardPaymentsMendixObject)
	{
		if (cardPaymentsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cardPaymentsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cardPaymentsMendixObject = cardPaymentsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static payappmodule.proxies.CardPayments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new payappmodule.proxies.CardPayments(context, mendixObject);
	}

	public static payappmodule.proxies.CardPayments load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return payappmodule.proxies.CardPayments.initialize(context, mendixObject);
	}

	public static java.util.List<payappmodule.proxies.CardPayments> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> payappmodule.proxies.CardPayments.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of CardPaymentID
	 */
	public final java.lang.Long getCardPaymentID()
	{
		return getCardPaymentID(getContext());
	}

	/**
	 * @param context
	 * @return value of CardPaymentID
	 */
	public final java.lang.Long getCardPaymentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CardPaymentID.toString());
	}

	/**
	 * Set value of CardPaymentID
	 * @param cardpaymentid
	 */
	public final void setCardPaymentID(java.lang.Long cardpaymentid)
	{
		setCardPaymentID(getContext(), cardpaymentid);
	}

	/**
	 * Set value of CardPaymentID
	 * @param context
	 * @param cardpaymentid
	 */
	public final void setCardPaymentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long cardpaymentid)
	{
		getMendixObject().setValue(context, MemberNames.CardPaymentID.toString(), cardpaymentid);
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.math.BigDecimal amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final payappmodule.proxies.Enum_TranscationStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final payappmodule.proxies.Enum_TranscationStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return payappmodule.proxies.Enum_TranscationStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(payappmodule.proxies.Enum_TranscationStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, payappmodule.proxies.Enum_TranscationStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of MerchantName
	 */
	public final java.lang.String getMerchantName()
	{
		return getMerchantName(getContext());
	}

	/**
	 * @param context
	 * @return value of MerchantName
	 */
	public final java.lang.String getMerchantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MerchantName.toString());
	}

	/**
	 * Set value of MerchantName
	 * @param merchantname
	 */
	public final void setMerchantName(java.lang.String merchantname)
	{
		setMerchantName(getContext(), merchantname);
	}

	/**
	 * Set value of MerchantName
	 * @param context
	 * @param merchantname
	 */
	public final void setMerchantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String merchantname)
	{
		getMendixObject().setValue(context, MemberNames.MerchantName.toString(), merchantname);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CardPayments_PaymentMethods
	 */
	public final payappmodule.proxies.PaymentMethods getCardPayments_PaymentMethods() throws com.mendix.core.CoreException
	{
		return getCardPayments_PaymentMethods(getContext());
	}

	/**
	 * @param context
	 * @return value of CardPayments_PaymentMethods
	 * @throws com.mendix.core.CoreException
	 */
	public final payappmodule.proxies.PaymentMethods getCardPayments_PaymentMethods(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		payappmodule.proxies.PaymentMethods result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CardPayments_PaymentMethods.toString());
		if (identifier != null) {
			result = payappmodule.proxies.PaymentMethods.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CardPayments_PaymentMethods
	 * @param cardpayments_paymentmethods
	 */
	public final void setCardPayments_PaymentMethods(payappmodule.proxies.PaymentMethods cardpayments_paymentmethods)
	{
		setCardPayments_PaymentMethods(getContext(), cardpayments_paymentmethods);
	}

	/**
	 * Set value of CardPayments_PaymentMethods
	 * @param context
	 * @param cardpayments_paymentmethods
	 */
	public final void setCardPayments_PaymentMethods(com.mendix.systemwideinterfaces.core.IContext context, payappmodule.proxies.PaymentMethods cardpayments_paymentmethods)
	{
		if (cardpayments_paymentmethods == null) {
			getMendixObject().setValue(context, MemberNames.CardPayments_PaymentMethods.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CardPayments_PaymentMethods.toString(), cardpayments_paymentmethods.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cardPaymentsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final payappmodule.proxies.CardPayments that = (payappmodule.proxies.CardPayments) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
