// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package payappmodule.proxies;

public class PaymentMethods implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paymentMethodsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PayAppModule.PaymentMethods";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Username("Username"),
		PayType("PayType"),
		HolderName("HolderName"),
		BankName("BankName"),
		BranchCode("BranchCode"),
		NumberOfAC("NumberOfAC"),
		ExpiryDate("ExpiryDate"),
		CVV("CVV"),
		PaymentMethods_Register("PayAppModule.PaymentMethods_Register");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PaymentMethods(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PaymentMethods(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paymentMethodsMendixObject)
	{
		if (paymentMethodsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, paymentMethodsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.paymentMethodsMendixObject = paymentMethodsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static payappmodule.proxies.PaymentMethods initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new payappmodule.proxies.PaymentMethods(context, mendixObject);
	}

	public static payappmodule.proxies.PaymentMethods load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return payappmodule.proxies.PaymentMethods.initialize(context, mendixObject);
	}

	public static java.util.List<payappmodule.proxies.PaymentMethods> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> payappmodule.proxies.PaymentMethods.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * Get value of PayType
	 * @param paytype
	 */
	public final payappmodule.proxies.Enum_PayType getPayType()
	{
		return getPayType(getContext());
	}

	/**
	 * @param context
	 * @return value of PayType
	 */
	public final payappmodule.proxies.Enum_PayType getPayType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PayType.toString());
		if (obj == null) {
			return null;
		}
		return payappmodule.proxies.Enum_PayType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PayType
	 * @param paytype
	 */
	public final void setPayType(payappmodule.proxies.Enum_PayType paytype)
	{
		setPayType(getContext(), paytype);
	}

	/**
	 * Set value of PayType
	 * @param context
	 * @param paytype
	 */
	public final void setPayType(com.mendix.systemwideinterfaces.core.IContext context, payappmodule.proxies.Enum_PayType paytype)
	{
		if (paytype != null) {
			getMendixObject().setValue(context, MemberNames.PayType.toString(), paytype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.PayType.toString(), null);
		}
	}

	/**
	 * @return value of HolderName
	 */
	public final java.lang.String getHolderName()
	{
		return getHolderName(getContext());
	}

	/**
	 * @param context
	 * @return value of HolderName
	 */
	public final java.lang.String getHolderName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HolderName.toString());
	}

	/**
	 * Set value of HolderName
	 * @param holdername
	 */
	public final void setHolderName(java.lang.String holdername)
	{
		setHolderName(getContext(), holdername);
	}

	/**
	 * Set value of HolderName
	 * @param context
	 * @param holdername
	 */
	public final void setHolderName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String holdername)
	{
		getMendixObject().setValue(context, MemberNames.HolderName.toString(), holdername);
	}

	/**
	 * @return value of BankName
	 */
	public final java.lang.String getBankName()
	{
		return getBankName(getContext());
	}

	/**
	 * @param context
	 * @return value of BankName
	 */
	public final java.lang.String getBankName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BankName.toString());
	}

	/**
	 * Set value of BankName
	 * @param bankname
	 */
	public final void setBankName(java.lang.String bankname)
	{
		setBankName(getContext(), bankname);
	}

	/**
	 * Set value of BankName
	 * @param context
	 * @param bankname
	 */
	public final void setBankName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bankname)
	{
		getMendixObject().setValue(context, MemberNames.BankName.toString(), bankname);
	}

	/**
	 * @return value of BranchCode
	 */
	public final java.lang.String getBranchCode()
	{
		return getBranchCode(getContext());
	}

	/**
	 * @param context
	 * @return value of BranchCode
	 */
	public final java.lang.String getBranchCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BranchCode.toString());
	}

	/**
	 * Set value of BranchCode
	 * @param branchcode
	 */
	public final void setBranchCode(java.lang.String branchcode)
	{
		setBranchCode(getContext(), branchcode);
	}

	/**
	 * Set value of BranchCode
	 * @param context
	 * @param branchcode
	 */
	public final void setBranchCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String branchcode)
	{
		getMendixObject().setValue(context, MemberNames.BranchCode.toString(), branchcode);
	}

	/**
	 * @return value of NumberOfAC
	 */
	public final java.lang.String getNumberOfAC()
	{
		return getNumberOfAC(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfAC
	 */
	public final java.lang.String getNumberOfAC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NumberOfAC.toString());
	}

	/**
	 * Set value of NumberOfAC
	 * @param numberofac
	 */
	public final void setNumberOfAC(java.lang.String numberofac)
	{
		setNumberOfAC(getContext(), numberofac);
	}

	/**
	 * Set value of NumberOfAC
	 * @param context
	 * @param numberofac
	 */
	public final void setNumberOfAC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numberofac)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfAC.toString(), numberofac);
	}

	/**
	 * @return value of ExpiryDate
	 */
	public final java.lang.String getExpiryDate()
	{
		return getExpiryDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpiryDate
	 */
	public final java.lang.String getExpiryDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ExpiryDate.toString());
	}

	/**
	 * Set value of ExpiryDate
	 * @param expirydate
	 */
	public final void setExpiryDate(java.lang.String expirydate)
	{
		setExpiryDate(getContext(), expirydate);
	}

	/**
	 * Set value of ExpiryDate
	 * @param context
	 * @param expirydate
	 */
	public final void setExpiryDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String expirydate)
	{
		getMendixObject().setValue(context, MemberNames.ExpiryDate.toString(), expirydate);
	}

	/**
	 * @return value of CVV
	 */
	public final java.lang.String getCVV()
	{
		return getCVV(getContext());
	}

	/**
	 * @param context
	 * @return value of CVV
	 */
	public final java.lang.String getCVV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CVV.toString());
	}

	/**
	 * Set value of CVV
	 * @param cvv
	 */
	public final void setCVV(java.lang.String cvv)
	{
		setCVV(getContext(), cvv);
	}

	/**
	 * Set value of CVV
	 * @param context
	 * @param cvv
	 */
	public final void setCVV(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cvv)
	{
		getMendixObject().setValue(context, MemberNames.CVV.toString(), cvv);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentMethods_Register
	 */
	public final payappmodule.proxies.Register getPaymentMethods_Register() throws com.mendix.core.CoreException
	{
		return getPaymentMethods_Register(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentMethods_Register
	 * @throws com.mendix.core.CoreException
	 */
	public final payappmodule.proxies.Register getPaymentMethods_Register(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		payappmodule.proxies.Register result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentMethods_Register.toString());
		if (identifier != null) {
			result = payappmodule.proxies.Register.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentMethods_Register
	 * @param paymentmethods_register
	 */
	public final void setPaymentMethods_Register(payappmodule.proxies.Register paymentmethods_register)
	{
		setPaymentMethods_Register(getContext(), paymentmethods_register);
	}

	/**
	 * Set value of PaymentMethods_Register
	 * @param context
	 * @param paymentmethods_register
	 */
	public final void setPaymentMethods_Register(com.mendix.systemwideinterfaces.core.IContext context, payappmodule.proxies.Register paymentmethods_register)
	{
		if (paymentmethods_register == null) {
			getMendixObject().setValue(context, MemberNames.PaymentMethods_Register.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentMethods_Register.toString(), paymentmethods_register.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paymentMethodsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final payappmodule.proxies.PaymentMethods that = (payappmodule.proxies.PaymentMethods) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
