// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package payappmodule.proxies;

public class TransactionsByAccount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transactionsByAccountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PayAppModule.TransactionsByAccount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TransactionID("TransactionID"),
		Username("Username"),
		Amount("Amount"),
		Date("Date"),
		Status("Status"),
		Description("Description"),
		CounterpartyName("CounterpartyName"),
		CounterpartyAccountNumber("CounterpartyAccountNumber"),
		Currency("Currency"),
		TransactionsByAccount_PaymentMethods("PayAppModule.TransactionsByAccount_PaymentMethods");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransactionsByAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TransactionsByAccount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionsByAccountMendixObject)
	{
		if (transactionsByAccountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, transactionsByAccountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.transactionsByAccountMendixObject = transactionsByAccountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static payappmodule.proxies.TransactionsByAccount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new payappmodule.proxies.TransactionsByAccount(context, mendixObject);
	}

	public static payappmodule.proxies.TransactionsByAccount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return payappmodule.proxies.TransactionsByAccount.initialize(context, mendixObject);
	}

	public static java.util.List<payappmodule.proxies.TransactionsByAccount> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> payappmodule.proxies.TransactionsByAccount.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of TransactionID
	 */
	public final java.lang.Long getTransactionID()
	{
		return getTransactionID(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionID
	 */
	public final java.lang.Long getTransactionID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TransactionID.toString());
	}

	/**
	 * Set value of TransactionID
	 * @param transactionid
	 */
	public final void setTransactionID(java.lang.Long transactionid)
	{
		setTransactionID(getContext(), transactionid);
	}

	/**
	 * Set value of TransactionID
	 * @param context
	 * @param transactionid
	 */
	public final void setTransactionID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long transactionid)
	{
		getMendixObject().setValue(context, MemberNames.TransactionID.toString(), transactionid);
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.math.BigDecimal amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final payappmodule.proxies.Enum_TranscationStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final payappmodule.proxies.Enum_TranscationStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return payappmodule.proxies.Enum_TranscationStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(payappmodule.proxies.Enum_TranscationStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, payappmodule.proxies.Enum_TranscationStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of CounterpartyName
	 */
	public final java.lang.String getCounterpartyName()
	{
		return getCounterpartyName(getContext());
	}

	/**
	 * @param context
	 * @return value of CounterpartyName
	 */
	public final java.lang.String getCounterpartyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CounterpartyName.toString());
	}

	/**
	 * Set value of CounterpartyName
	 * @param counterpartyname
	 */
	public final void setCounterpartyName(java.lang.String counterpartyname)
	{
		setCounterpartyName(getContext(), counterpartyname);
	}

	/**
	 * Set value of CounterpartyName
	 * @param context
	 * @param counterpartyname
	 */
	public final void setCounterpartyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String counterpartyname)
	{
		getMendixObject().setValue(context, MemberNames.CounterpartyName.toString(), counterpartyname);
	}

	/**
	 * @return value of CounterpartyAccountNumber
	 */
	public final java.lang.String getCounterpartyAccountNumber()
	{
		return getCounterpartyAccountNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CounterpartyAccountNumber
	 */
	public final java.lang.String getCounterpartyAccountNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CounterpartyAccountNumber.toString());
	}

	/**
	 * Set value of CounterpartyAccountNumber
	 * @param counterpartyaccountnumber
	 */
	public final void setCounterpartyAccountNumber(java.lang.String counterpartyaccountnumber)
	{
		setCounterpartyAccountNumber(getContext(), counterpartyaccountnumber);
	}

	/**
	 * Set value of CounterpartyAccountNumber
	 * @param context
	 * @param counterpartyaccountnumber
	 */
	public final void setCounterpartyAccountNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String counterpartyaccountnumber)
	{
		getMendixObject().setValue(context, MemberNames.CounterpartyAccountNumber.toString(), counterpartyaccountnumber);
	}

	/**
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final java.lang.String getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Currency.toString());
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(java.lang.String currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currency)
	{
		getMendixObject().setValue(context, MemberNames.Currency.toString(), currency);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionsByAccount_PaymentMethods
	 */
	public final payappmodule.proxies.PaymentMethods getTransactionsByAccount_PaymentMethods() throws com.mendix.core.CoreException
	{
		return getTransactionsByAccount_PaymentMethods(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionsByAccount_PaymentMethods
	 * @throws com.mendix.core.CoreException
	 */
	public final payappmodule.proxies.PaymentMethods getTransactionsByAccount_PaymentMethods(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		payappmodule.proxies.PaymentMethods result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionsByAccount_PaymentMethods.toString());
		if (identifier != null) {
			result = payappmodule.proxies.PaymentMethods.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionsByAccount_PaymentMethods
	 * @param transactionsbyaccount_paymentmethods
	 */
	public final void setTransactionsByAccount_PaymentMethods(payappmodule.proxies.PaymentMethods transactionsbyaccount_paymentmethods)
	{
		setTransactionsByAccount_PaymentMethods(getContext(), transactionsbyaccount_paymentmethods);
	}

	/**
	 * Set value of TransactionsByAccount_PaymentMethods
	 * @param context
	 * @param transactionsbyaccount_paymentmethods
	 */
	public final void setTransactionsByAccount_PaymentMethods(com.mendix.systemwideinterfaces.core.IContext context, payappmodule.proxies.PaymentMethods transactionsbyaccount_paymentmethods)
	{
		if (transactionsbyaccount_paymentmethods == null) {
			getMendixObject().setValue(context, MemberNames.TransactionsByAccount_PaymentMethods.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionsByAccount_PaymentMethods.toString(), transactionsbyaccount_paymentmethods.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transactionsByAccountMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final payappmodule.proxies.TransactionsByAccount that = (payappmodule.proxies.TransactionsByAccount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
